### ISSUE TITLE
Counter to rush on main page

### ISSUE THREAD

**Issue by Akshat30** [sdakpsi/RushWebsite#11]
On the main page, add a counter that counts down the days, hours, minutes, and seconds until rush. The time to countdown to is September 30th, 2024, at 6 PM.

When creating the branch for this issue, make sure to choose dev as the branch source. Then switch to the newly created branch when working on the code.

The code for the main page resides in /app/page.tsx.

Should look something like this, with seconds as well:
<img width="393" alt="image" src="https://github.com/user-attachments/assets/ac63160f-05b1-4c71-9c22-ebc3cee3de75">

**Comment by EeswarK** [comment]
#24 Closes this issue

**Comment by EeswarK** [comment]
#24 Closes this issue
